apiVersion: user5.qiot.io/v1alpha1
kind: Datacenter
metadata:
  name: qiotdctest
  namespace: default
spec:
  registry: "quay.io/qiotmanufacturing/"
  kafkaBootstrapURL: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  sizing: 1
  registrationService:
    image: "datacenter-registration"
    version: "latest"
    logLevel: "INFO"
  plantManagerService:
    image: "datacenter-plant-manager"
    version: "latest"
    logLevel: "INFO"
  globalProductLineService:
    image: "datacenter-product-line"
    version: "latest"
    logLevel: "DEBUG"
  eventCollectorService:
    image: "datacenter-event-collector-jvm"
    version: "latest"
    logLevel: "INFO"
